FROM alpine:latest

RUN apk add --no-cache \
    curl \
    jq \
    gzip \
    tar \
    coreutils \
    dcron \
    rsync

COPY backup.sh /app/backup.sh
COPY entrypoint.sh /app/entrypoint.sh

RUN chmod +x /app/backup.sh /app/entrypoint.sh

WORKDIR /app

ENTRYPOINT ["/app/entrypoint.sh"]
